### ISSUE TITLE
Can’t see disconnected clients

### ISSUE THREAD

**Issue by dodoria15** [FarisCode511/BlackNET#10]
for some reason it doesn’t show me client disconnecting ,
It’s shows me all the time clients that is online , but can’t see disconnections the number just went up 
I think even if they not online
It’s show they are ..

**Comment by FarisCode511** [comment]
> for some reason it doesn’t show me client disconnecting ,
> It’s shows me all the time clients that is online , but can’t see disconnections the number just went up
> I think even if they not online
> It’s show they are ..

Please explain more and add some screenshots from the panel

**Comment by FarisCode511** [comment]
As I explained hundreds of times you need setup cronjobs for both ping.php and remove.php

follow this video

https://www.youtube.com/watch?v=rHCYGRA1h54

**Comment by dodoria15** [comment]
Ok I did it and it worked
But for some reason it’s
Showing me
50 clients online 750 offline 
When at the remote tool other one I have they online

**Comment by FarisCode511** [comment]
Will it means for some reason the malware got detected by the antivirus because the ping.php job is to check if a client is unresponsive for more than an hour then changes its status to offline and the remove.php job is to remove all offline clients
