### ISSUE TITLE
Cant steal password

### ISSUE THREAD

**Issue by oraclethunder** [FarisCode511/BlackNET#13]
after crypting with a crypter it does not steal password have issue with .net framework

**Comment by FarisCode511** [comment]
What is the crypter

**Comment by oraclethunder** [comment]
Cyber seal, Allien, Data encoder, data protect also, even when converted to macro doc it doesn't get any result

**Comment by arsium** [comment]
Hello I decompile Passwords Plugin and nothing is working anymore (outdated ?)

**Comment by arsium** [comment]
If you need help with your plugin , I will be proud to help you

**Comment by FarisCode511** [comment]
@arsium it is not outdated I already tested with the latest chrome and firefox and It is working without issues

**Comment by FarisCode511** [comment]
@arsium if you see any issue I dont see then why not

**Comment by arsium** [comment]
I've decompiled it with lastest chrome and firefox I added it in an other test project to see if it works but I don't get success (with my own plugin yes):(

**Comment by FarisCode511** [comment]
> I've decompiled it with lastest chrome and firefox I added it in an other test project to see if it works but I don't get success (with my own plugin yes):(

I will look into it it might something wrong with the plugin, if I find any issues it will be fixed and updated in the next release. and If you find anything with the plugin code because as you say you decompiled it then you can just send the fix to my email: farisksa79@protonmail.com

Enjoy.

**Comment by oraclethunder** [comment]
the issue is from version of net framework but i think you have fixed it on
the update you gave

‪On Mon, Dec 7, 2020 at 10:18 AM ថಘઅഞפּ ṛཥચ <notifications@github.com>
wrote:‬
