### ISSUE TITLE
DropBox and OneDrive spread?

### ISSUE THREAD

**Issue by LimerBoy** [FarisCode511/BlackNET#14]
What do you think of the botnet spread feature via OneDrive and DropBox?

[it was in the second version](https://github.com/therealelyayo/BlackNET-2/blob/master/BlackNET%20-%20Source%20Code/PHPStub/PHPStub/Spreads/DropboxSpread.vb)

**Comment by FarisCode511** [comment]
A good idea the old code was buggy and had issues I will try to update it and reImplement it and will try to add OneDrive Support to it.
