### ISSUE TITLE
Can't login after installing blacknet panel.

### ISSUE THREAD

**Issue by Totem112** [FarisCode511/BlackNET#15]
When i try to login into the main panel, nothing happens, if i write a wrong username or passwords it warns that something is not correct, otherwise if i enter the correct credentials, just nothing happens.
I already gave 777 permissions to all files in 000webhost.
I saw anothe user having the same problem but no solution privided publicly.

Any help is wellcomed.

Thanks.

**Comment by FarisCode511** [comment]
Send me a Telegram @ BlackHacker511 with access to your 000webhosting account.

**Comment by Totem112** [comment]
I managed to make it work. I created a new 000webhost account wuthout any google account linked, I followed the instalation process and its worked. Idk if that was the issue but it worked for me.
