### ISSUE TITLE
Client Connects for 1 sek

### ISSUE THREAD

**Issue by Sh4r3cat** [FarisCode511/BlackNET#19]
hey in the botnet log i see a client connects after that i runned the client as debugmode
and got this error [29.11.2020 02:26:45]: Der Remoteserver hat einen Fehler zurückgegeben: (500) Interner Serverfehler.
[29.11.2020 02:27:50]: Der Remoteserver hat einen Fehler zurückgegeben: (500) Interner Serverfehler.

**Comment by Sh4r3cat** [comment]
btw i host it at 000webhost

**Comment by Sh4r3cat** [comment]
then i run it as admin the 000webhost site is blank and i cant see if iam connected

**Comment by FarisCode511** [comment]
Hey, send me a Telegram @ BlackHacker_511 with access to your 000webhost account.
