### ISSUE TITLE
What do i do now XD

### ISSUE THREAD

**Issue by TheAwesomeM2** [FarisCode511/BlackNET#2]
error while building from source

Severity	Code	Description	Project	File	Line	Suppression State
Error		Type 'ModuleDefinition' is not defined.	BlackNet Builder	C:\Users\TheYellinFrs\Desktop\BlackNET - Source Code\BlackNet Builder\BlackNet Builder\Main.vb	59	
Error		Type 'AssemblyDefinition' is not defined.	BlackNet Builder	C:\Users\TheYellinFrs\Desktop\BlackNET - Source Code\BlackNet Builder\BlackNet Builder\Main.vb	57	
Error		'AssemblyDefinition' is not declared. It may be inaccessible due to its protection level.	BlackNet Builder	C:\Users\TheYellinFrs\Desktop\BlackNET - Source Code\BlackNet Builder\BlackNet Builder\Main.vb	58	
Error		Type 'TypeDefinition' is not defined.	BlackNet Builder	C:\Users\TheYellinFrs\Desktop\BlackNET - Source Code\BlackNet Builder\BlackNet Builder\Main.vb	61	
Error		Type 'MethodDefinition' is not defined.	BlackNet Builder	C:\Users\TheYellinFrs\Desktop\BlackNET - Source Code\BlackNet Builder\BlackNet Builder\Main.vb	63	
Error		Type 'Instruction' is not defined.	BlackNet Builder	C:\Users\TheYellinFrs\Desktop\BlackNET - Source Code\BlackNet Builder\BlackNet Builder\Main.vb	66	
Error		Type 'Instruction' is not defined.	BlackNet Builder	C:\Users\TheYellinFrs\Desktop\BlackNET - Source Code\BlackNet Builder\BlackNet Builder\Main.vb	70	
Error		'Code' is not declared. It may be inaccessible due to its protection level.	BlackNet Builder	C:\Users\TheYellinFrs\Desktop\BlackNET - Source Code\BlackNet Builder\BlackNet Builder\Main.vb	71

**Comment by FarisCode511** [comment]
Fixing this issue is easy just copy Mono.Cecil.dll from the compiled version to BlackNET - Source Code\BlackNet Builder\BlackNet Builder\bin\Debug and then recompile the source code
