### ISSUE TITLE
Password Stealer doesn't work

### ISSUE THREAD

**Issue by iii235** [FarisCode511/BlackNET#20]
**Describe the bug**
I ran the password stealer on my own pc, but the passwords it got (Google Chrome) is just in the form of random, garbage text.

**To Reproduce**
1. Install BlackNET Client (Crypted with NK crypter, which required visual studio to crypt)
2. Run password stealer

**Expected behavior**
My Passwords in the txt file in cleartext.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows 10 Home
 - Browser Google Chrome
 - Version Don't know.

**Comment by FarisCode511** [comment]
Could you please click on the client name and then click on the download link next to Passwords.txt it will decode this garbage text and present it in clean table

**Comment by FarisCode511** [comment]
And no the excepted behavior is not your password in clear this will compromise your credentials

The real expected behavior is your passwords encoded in base64 in the text file that's why there is a password viewer

Enjoy

**Comment by iii235** [comment]
Sorry man. I understand now.

**Comment by FarisCode511** [comment]
No problem.

Enjoy
