### ISSUE TITLE
Install.php blue button not active

### ISSUE THREAD

**Issue by dieabetes** [FarisCode511/BlackNET#21]
just as the title says, did everythin in the instructions, everything seemed ok, filled out the form, but I can't click on the blue button

**Comment by FarisCode511** [comment]
This is the commit that fixes the problem

https://github.com/FarisCode511/BlackNET/blob/56d425ef51e10b8171d1b06756ab9ecc9d60633a/BlackNET%20Panel/install.php

Implement it and it should work
