### ISSUE TITLE
No interface

### ISSUE THREAD

**Issue by nicken648** [FarisCode511/BlackNET#26]
I have a problem that my BlackNET does not have an interface.Please help me
![Screenshot_1](https://user-images.githubusercontent.com/65249766/101994159-f32c3180-3ce1-11eb-93c9-3e918c546c6d.png)

**Comment by LimerBoy** [comment]
try reinstall panel

**Comment by nicken648** [comment]
already tried

**Comment by FarisCode511** [comment]
Hey,

What is hosting do you use?

Did you try to give all files and folders 777 permissions especially the "assets" folder?

**Comment by nicken648** [comment]
I am using webhost 000hosting
I gave all folders permission 777 did not help

**Comment by FarisCode511** [comment]
I will make a video on how to install the panel

Just give me an hour or two and it will be on my YouTube channel.

**Comment by FarisCode511** [comment]
> I am using 000webhost hosting
> I gave all folders permission 777 did not help

Watch this video

https://youtu.be/0IU_64yfL80
