### ISSUE TITLE
No css or js on the panel

### ISSUE THREAD

**Issue by Willto-hf** [FarisCode511/BlackNET#29]
Crazyrdp
Vps
The first picture is the login screen
The second picture is after I typed the credentials
And the last picture is after I removed the middle line in the url which let me move into the panel.
![Loging screen](https://user-images.githubusercontent.com/75954562/102025690-01d61f80-3d9a-11eb-9568-77b34a896691.png)
![After Login](https://user-images.githubusercontent.com/75954562/102025694-069ad380-3d9a-11eb-91f5-f4387c855e9b.png)
![After I removed the middle line in the URL](https://user-images.githubusercontent.com/75954562/102025697-0995c400-3d9a-11eb-8d17-21a3650a1902.png)

**Comment by FarisCode511** [comment]
#26 Same issue and I already answered it

Watch this video
https://youtu.be/0IU_64yfL80

Enjoy
