### ISSUE TITLE
Clients are not visible 

### ISSUE THREAD

**Issue by TheAwesomeM2** [FarisCode511/BlackNET#3]
i have installed my botnet into the latest XAMPP but once i run the client.exe on someone on my network a connection appears in the logs but not in the panel is there any way to fix this oh and how do i use this over the network without using a external website/server

**Comment by Kydaix** [comment]
Did you set Cron Jobs?

**Comment by FarisCode511** [comment]
1. Enable Debug Mode
2. Check for error_logs
3. Expose XAMPP to the internet (Google It)

if the error_logs has any log file attach it and if the logs.txt has any thing in it attach it to

**Comment by TheAwesomeM2** [comment]
ok ill check again and ill send an update

**Comment by TheAwesomeM2** [comment]
there is a thing called php_script_error.log

**Comment by TheAwesomeM2** [comment]
[31-Oct-2020 21:38:01 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in D:\xampp\htdocs\bnet_panel\classes\Database.php:128
Stack trace:
#0 D:\xampp\htdocs\bnet_panel\classes\Update.php(194): Database->query('CREATE TABLE IF...')
#1 D:\xampp\htdocs\bnet_panel\logic\installLogic.php(169): Update->execute('CREATE TABLE IF...')
#2 D:\xampp\htdocs\bnet_panel\install.php(5): include_once('D:\\xampp\\htdocs...')
#3 {main}
  thrown in D:\xampp\htdocs\bnet_panel\classes\Database.php on line 128
[31-Oct-2020 21:38:13 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in D:\xampp\htdocs\bnet_panel\classes\Database.php:128
Stack trace:
#0 D:\xampp\htdocs\bnet_panel\classes\Update.php(194): Database->query('CREATE TABLE IF...')
#1 D:\xampp\htdocs\bnet_panel\logic\installLogic.php(169): Update->execute('CREATE TABLE IF...')
#2 D:\xampp\htdocs\bnet_panel\install.php(5): include_once('D:\\xampp\\htdocs...')
#3 {main}
  thrown in D:\xampp\htdocs\bnet_panel\classes\Database.php on line 128
[31-Oct-2020 21:42:32 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bnet.settings' doesn't exist in D:\xampp\htdocs\bnet_panel\classes\Database.php:138
Stack trace:
#0 D:\xampp\htdocs\bnet_panel\classes\Database.php(138): PDOStatement->execute()
#1 D:\xampp\htdocs\bnet_panel\classes\Settings.php(41): Database->execute()
#2 D:\xampp\htdocs\bnet_panel\logic\loginLogic.php(16): Settings->getSettings()
#3 D:\xampp\htdocs\bnet_panel\login.php(9): include_once('D:\\xampp\\htdocs...')
#4 {main}
  thrown in D:\xampp\htdocs\bnet_panel\classes\Database.php on line 138
[31-Oct-2020 21:42:35 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bnet.settings' doesn't exist in D:\xampp\htdocs\bnet_panel\classes\Database.php:138
Stack trace:
#0 D:\xampp\htdocs\bnet_panel\classes\Database.php(138): PDOStatement->execute()
#1 D:\xampp\htdocs\bnet_panel\classes\Settings.php(41): Database->execute()
#2 D:\xampp\htdocs\bnet_panel\logic\loginLogic.php(16): Settings->getSettings()
#3 D:\xampp\htdocs\bnet_panel\login.php(9): include_once('D:\\xampp\\htdocs...')
#4 {main}
  thrown in D:\xampp\htdocs\bnet_panel\classes\Database.php on line 138
[31-Oct-2020 21:46:16 Europe/Berlin] PHP Fatal error:  Uncaught GeoIp2\Exception\AddressNotFoundException: The address 192.168.1.44 is not in the database. in phar://D:/xampp/htdocs/bnet_panel/vendor/geoip/geoip2.phar/src/Database/Reader.php:234
Stack trace:
#0 phar://D:/xampp/htdocs/bnet_panel/vendor/geoip/geoip2.phar/src/Database/Reader.php(203): GeoIp2\Database\Reader->getRecord('City', 'City', '192.168.1.44')
#1 phar://D:/xampp/htdocs/bnet_panel/vendor/geoip/geoip2.phar/src/Database/Reader.php(73): GeoIp2\Database\Reader->modelFor('City', 'City', '192.168.1.44')
#2 D:\xampp\htdocs\bnet_panel\connection.php(49): GeoIp2\Database\Reader->city('192.168.1.44')
#3 D:\xampp\htdocs\bnet_panel\connection.php(14): getConteryCode('192.168.1.44')
#4 {main}
  thrown in phar://D:/xampp/htdocs/bnet_panel/vendor/geoip/geoip2.phar/src/Database/Reader.php on line 234
[01-Nov-2020 21:59:08 Europe/Berlin] PHP Fatal error:  Uncaught GeoIp2\Exception\AddressNotFoundException: The address 192.168.1.44 is not in the database. in phar://D:/xampp/htdocs/bnet_panel/vendor/geoip/geoip2.phar/src/Database/Reader.php:234
Stack trace:
#0 phar://D:/xampp/htdocs/bnet_panel/vendor/geoip/geoip2.phar/src/Database/Reader.php(203): GeoIp2\Database\Reader->getRecord('City', 'City', '192.168.1.44')
#1 phar://D:/xampp/htdocs/bnet_panel/vendor/geoip/geoip2.phar/src/Database/Reader.php(73): GeoIp2\Database\Reader->modelFor('City', 'City', '192.168.1.44')
#2 D:\xampp\htdocs\bnet_panel\connection.php(49): GeoIp2\Database\Reader->city('192.168.1.44')
#3 D:\xampp\htdocs\bnet_panel\connection.php(14): getConteryCode('192.168.1.44')
#4 {main}
  thrown in phar://D:/xampp/htdocs/bnet_panel/vendor/geoip/geoip2.phar/src/Database/Reader.php on line 234

**Comment by FarisCode511** [comment]
OK I see the issue the GeoIP Reader does not recognize the IP because it's from inside the network, please use it with a hosting and try again.

**Comment by TheAwesomeM2** [comment]
but it would normally work outside the network?

**Comment by FarisCode511** [comment]
> but it would normally work outside the network?

Yes.
