### ISSUE TITLE
Сrash site

### ISSUE THREAD

**Issue by nicken648** [FarisCode511/BlackNET#30]
I have a problem with the site crashing, I do not know what it is all about, it may crash when I add more than 2 clients or after a certain amount of time
Cleaning the cache does not help
And more than 2 clients do not appear in my house, and the logs say that they have connected
(I did everything on video)
![Capture](https://user-images.githubusercontent.com/65249766/102043649-d1709e80-3df6-11eb-85b2-4e5fd91349d6.PNG)

**Comment by FarisCode511** [comment]
000webhost

If yes then that is a 000webhost problem

query limit restriction.

Get a decent bulletproof hosting.
