### ISSUE TITLE
cannot click on "start installation" on .install.php

### ISSUE THREAD

**Issue by peebeekay89** [FarisCode511/BlackNET#4]
I uploaded the panel, changed config.php, changed permissions and everything...filled out the username password and email and when i go to hit start installation it doesn't do anything. Nothing at all. any help would be greatly appreacited!

**Comment by FarisCode511** [comment]
Yes take a screenshot of the install page and attach it here

**Comment by FarisCode511** [comment]
I will assume that all libs are installed then just update PHP to 7.3 or up.
