### ISSUE TITLE
Password stealer

### ISSUE THREAD

**Issue by peebeekay89** [FarisCode511/BlackNET#5]
When I run Password stealer for any bot I recieve this in logs

Password Stealer has been execute

then

Password Stelaer failed in collecting passwords

Is there something i amd oing wrong or is it not working properly or?

**Comment by FarisCode511** [comment]
Will it means either the password stealer did not find any password on the client machine or it got detected by the client machine 

if the client does not have any saved passwords you will get the same message.

**Comment by TomerGamerTV** [comment]
> Will it means either the password stealer did not find any password on the client machine or it got detected by the client machine
> 
> if the client does not have any saved passwords you will get the same message.

what is your Twitter? i want to talk with you

**Comment by FarisCode511** [comment]
> > Will it means either the password stealer did not find any password on the client machine or it got detected by the client machine
> > if the client does not have any saved passwords you will get the same message.
> 
> what is your Twitter? i want to talk with you

I don't have a Twitter account we can send me a message on Instagram @fariscode

**Comment by TomerGamerTV** [comment]
> > > Will it means either the password stealer did not find any password on the client machine or it got detected by the client machine
> > > if the client does not have any saved passwords you will get the same message.
> > 
> > 
> > what is your Twitter? i want to talk with you
> 
> I don't have a Twitter account we can send me a message on Instagram @FarisCode

i found another problem i will dm you in instagram
