### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by blackteam1** [FarisCode511/BlackNET#7]
I can't install the panel on hosting and on virtual hosts such as openserver and xampp when entering data after clicking the install button the http error 500 error POPs up can you upload a backup of a clean database?

**Comment by FarisCode511** [comment]
1. Screenshot of install page
2. If error_logs folder has a log file attach it here
3. Screenshot of config.php file

**Comment by FarisCode511** [comment]
> I can't install the panel on hosting and on virtual hosts such as openserver and xampp when entering data after clicking the install button the http error 500 error POPs up can you upload a backup of a clean database?

There is no clean database backup the installer uses a custom system to install the tables depending on your SQL Manager

Please provide
1. Screenshot of install page
2. If error_logs folder has a log file attach it here
3. Screenshot of config.php file
